github::fetch_repos(): Fetch all repos from all pages
Also switch from `reqwest::blocking` to async because I was getting this
error, probably because I call `fetch_repos()` in the async 'tokio'
function `main()`:

    thread 'main' panicked at 'Cannot drop a runtime in a context where
    blocking is not allowed. This happens when a runtime is dropped from
    within an asynchronous context.',
    $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/blocking/shutdown.rs:51:21